version: '3'

services:
  qqmusic:
    build: 
      context: .
      args:
        USER_ID: ${USER_ID}
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=${USER_DBUS_SESSION_BUS_ADDRESS}
      - PULSE_SERVER=unix:${USER_PULSE_SERVER}
      - DISPLAY
      - XAUTHORITY=/home/user/.Xauthority
    volumes:
      - "${USER_HOME}/.Xauthority:/home/user/.Xauthority:ro"
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - "${USER_DBUS_SESSION_BUS_ADDRESS}:${USER_DBUS_SESSION_BUS_ADDRESS}"
      - "${USER_PULSE_SERVER}:${USER_PULSE_SERVER}"
    hostname: ${HOSTNAME}
    command: 'qqmusic --no-xshm --no-sandbox'
    shm_size: 2gb
